//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alışveriş_Uygulaması
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategori
    {
        public int KategoriID { get; set; }
        public string Kategori_Adi { get; set; }
        public string Kategori_Tanim { get; set; }
    }
}
