//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alışveriş_Uygulaması
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kuryeler
    {
        public int KuryeID { get; set; }
        public string Kurye_Sirketi { get; set; }
        public string Kurye_Adi { get; set; }
        public string Kurye_Telefon { get; set; }
    }
}
