//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alışveriş_Uygulaması
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        public int MusteriID { get; set; }
        public string Musteri_Adi { get; set; }
        public string Musteri_Adres { get; set; }
        public string Musteri_Telefon { get; set; }
        public string Musteri_Sehir { get; set; }
        public string Musteri_KullaniciAdi { get; set; }
        public string Musteri_Sifre { get; set; }
        public string Musteri_MailAdresi { get; set; }
        public bool AdminYetkisi { get; set; }
    }
}
