//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alışveriş_Uygulaması
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satislar
    {
        public int SatisID { get; set; }
        public int MusteriID { get; set; }
        public string Satis_Tarihi { get; set; }
        public int Satis_OdenenTutar { get; set; }
        public int Satis_KuryeUcreti { get; set; }
        public string Satis_Adresi { get; set; }
        public int KuryeID { get; set; }
        public string UrunAdlari { get; set; }
        public int UrunID { get; set; }
    
        public virtual Kuryeler Kuryeler { get; set; }
        public virtual Musteriler Musteriler { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
