//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alışveriş_Uygulaması
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int UrunID { get; set; }
        public string Urun_Adi { get; set; }
        public int KategoriID { get; set; }
        public int Urun_Fiyati { get; set; }
        public int Urun_StokDuzeyi { get; set; }
        public string UrunAciklama { get; set; }
        public string Urun_image { get; set; }
    }
}
